<a href="https://colab.research.google.com/github/saroj321r-cmd/Data-Science-/blob/main/Join%26pivot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd

df1 = pd.DataFrame({
    'id':[1,2,3,4],
    'name':['JIN','JIHOO','THEV','JIMIN'],
    'age':[23,24,22,23]
})

df2 = pd.DataFrame({
    'id':[3,4,5,6],
    'name':['SUGA','Jhope','KOOKIE','RM'],
    'age':[23,24,22,23]
})

df3 = pd.merge(df1,df2,on = 'id',how = 'inner')  #inner join
print(df3)

df3.rename(columns={"name_x": "table_name1"},inplace = True)
print(df3)

df3 = pd.merge(df1,df2,on = 'id',how = 'left')  #left join
print(df3)

df3 = pd.merge(df1,df2,on = 'id',how = 'right')  #right join
print(df3)

df3 = pd.merge(df1,df2,on = 'id',how = 'outer')  #outer join
print(df3)

df3 = pd.merge(df1,df2,how = 'cross')  #cross join
print(df3)

df3 = pd.concat([df1,df2])
print(df3)


df4 = df1.drop_duplicates(subset = ['id'],keep = 'first')
df4

   id name_x  age_x name_y  age_y
0   3   THEV     22   SUGA     23
1   4  JIMIN     23  Jhope     24
   id table_name1  age_x name_y  age_y
0   3        THEV     22   SUGA     23
1   4       JIMIN     23  Jhope     24
   id name_x  age_x name_y  age_y
0   1    JIN     23    NaN    NaN
1   2  JIHOO     24    NaN    NaN
2   3   THEV     22   SUGA   23.0
3   4  JIMIN     23  Jhope   24.0
   id name_x  age_x  name_y  age_y
0   3   THEV   22.0    SUGA     23
1   4  JIMIN   23.0   Jhope     24
2   5    NaN    NaN  KOOKIE     22
3   6    NaN    NaN      RM     23
   id name_x  age_x  name_y  age_y
0   1    JIN   23.0     NaN    NaN
1   2  JIHOO   24.0     NaN    NaN
2   3   THEV   22.0    SUGA   23.0
3   4  JIMIN   23.0   Jhope   24.0
4   5    NaN    NaN  KOOKIE   22.0
5   6    NaN    NaN      RM   23.0
    id_x name_x  age_x  id_y  name_y  age_y
0      1    JIN     23     3    SUGA     23
1      1    JIN     23     4   Jhope     24
2      1    JIN     23     5  KOOKIE     22
3      1    JIN     23     6      RM     23
4      2  JIHOO     24     3    SUGA     23
5      2  JIHOO     24     4   Jhope     24
6      2  JIHOO     24     5  KOOKIE     22
7      2  JIHOO     24     6      RM     23
8      3   THEV     22     3    SUGA     23
9      3   THEV     22     4   Jhope     24
10     3   THEV     22     5  KOOKIE     22
11     3   THEV     22     6      RM     23
12     4  JIMIN     23     3    SUGA     23
13     4  JIMIN     23     4   Jhope     24
14     4  JIMIN     23     5  KOOKIE     22
15     4  JIMIN     23     6      RM     23
   id    name  age
0   1     JIN   23
1   2   JIHOO   24
2   3    THEV   22
3   4   JIMIN   23
0   3    SUGA   23
1   4   Jhope   24
2   5  KOOKIE   22
3   6      RM   23

   id   name  age
0   1    JIN   23
1   2  JIHOO   24
2   3   THEV   22
3   4  JIMIN   23

In [17]:
import pandas as pd

df = pd.read_csv('student_data.csv')
df
#df.pivot_table(columns = 'placement_status', index = 'sleep_hours' , values = 'exam_score', aggfunc= 'mean')

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
#1327 511 586 175 182 262 184 185 1179  questions of pivot tables

In [18]:
import pandas as pd

df = pd.read_csv('student_data.csv')
df.pivot_table(columns = 'study_hours', index = 'sleep_hours' , values = 'assignments_completed', aggfunc= 'mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844